name: Test CI

concurrency:
  group: ${{ github.workflow }}#${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  draft_pr_reminder:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' 
      && github.event.action == 'opened' 
      && github.event.pull_request.draft }}
    steps:
      - name: Add comment to PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Friendly reminder, CI workflows in draft PR's only run on ubuntu-20.04.
          reactions: eyes
  ci:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.config.foo }}
    strategy:
      matrix:
        os: [ macOS-11, ubuntu-20.04]
        config:
          - {"foo": "bar"}
          - {"foo": "baz"}
        include:
          - os: ubuntu-22.04
            config:
              foo: "fish"
    steps:
      - name: filter step
        id: run_on_this_platform
        if: ${{ !github.event.pull_request.draft || matrix.os == 'ubuntu-20.04' }}
        run: |
          echo "${{ matrix.os }}"
          echo "${{ matrix.config.foo }}"
      - name: actual work
        if: steps.run_on_this_platform.outcome == 'success'
        run: |
          echo "doing real work here."
          sleep 60
          echo "done"
